name: Pull Request Prerelease

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  prerelease:
    name: Pull Request Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=22.6.0"

      - name: Install dependencies with cache
        uses: bahmutov/npm-install@v1

      - name: Build and publish to pkg.pr.new
        run: npm run pkg-pr-new-publish
